print("git config --global user.name 'Teyit' ")
print("git config --global user.email ajimamatovteyitbek@gmail.com ")
print("git init")
print("mkdir - make directory (cd - got to path) ")
print("touch fileName - make file ")
print("vim - open file")
print("Hello from GitHub")
print("restore - last changes we can before add & commit")
print("diff - show last changes (+ - values) ")
