print("git config --global user.name 'Teyit' ")
print("git config --global user.email ajimamatovteyitbek@gmail.com ")
print("git init")
print("mkdir - make directory (cd - got to path) ")
print("touch fileName - make file ")
print("vim - open file")
print("Hello from GitHub")
print("restore - last changes we can before add & commit")
print("git diff - show last changes (+ - values) ")
print("git diff --staged  - show changes after 'git add' (in index) ")
print("git log  - show commits ")
print("i = print, (esc + : + x) = save")
print("git commit -am "message"  - add & commit")
print("git mv fileName /Folder/user  - replace")
print("git restore --staged filename   - cancel last changes in index ")
 
